### ISSUE TITLE
initially show end of the log with a link to the whole log

### ISSUE THREAD

**Issue by claymccoy** [atomist/rolar#11]
Currently we retrieve and show the whole log.  This can be quite time consuming to make all the calls to get the content from s3.  And usually the most recent part of the log is more relevant. So we are making the user wait on earlier log entries that they don't care about, and then making them scroll down.
Instead we could load the last bit of the long (last 50-100 lines or so), and give them an option to see the whole thing. This isn't a huge change but could make it much less frustrating.

**Comment by claymccoy** [comment]
@whostolebenfrog @cdupuis what do you think?

**Comment by whostolebenfrog** [comment]
I think this sounds a lot better. It's much nicer to see something right away. We could start loading the rest of the log once the user lands - to speed that part up too.

Good idea.

**Comment by cdupuis** [comment]
Why wouldn't the opposite just work too. Show the first couple of lines and then append the rest as it becomes available?

**Comment by claymccoy** [comment]
That would work too. It just seems like the more recent logs are typically more useful.

**Comment by cdupuis** [comment]
that UX would be strange, wouldn't it?

**Comment by claymccoy** [comment]
I guess that is subjective. This is how other tools work. Logzio for example, just shows a recent time window by default.

**Comment by cdupuis** [comment]
True, logzio does that. But travis etc don't do it. 

logzio also has the newest on top which makes sense if you display it like that but that won't work for us, eg. Spring Boot banner etc.

**Comment by cdupuis** [comment]
> We do start with the beginning, and then append log events as they come in currently. But if it is an existing log and it has a lot of history, then that first load can take a while. I'm just saying that we truncate some of that history unless they ask for it.

That's the part I don't understand, why not retrieve the first 10-30 lines send them over and keep adding; even for an existing log?

**Comment by claymccoy** [comment]
Because once you have thousands of lines you probably don't care about the ones at the beginning. Let's go ahead and show them the good part as soon as we can. My bet is that they usually care more about what just happened.

**Comment by claymccoy** [comment]
For example, why wait for everything to load if you are just going to have to scroll down to the bottom to see why your build failed.

**Comment by cdupuis** [comment]
I guess we can try it. But then you would have to change the dashboard code too.

**Comment by claymccoy** [comment]
> That's the part I don't understand, why not retrieve the first 10-30 lines send them over and keep adding; even for an existing log?
There is no reason that we don't do that. We just currently grab everything that is there because it was easy. This was my . first thought . was to make that first load iterative as well. And then my . second . thought was why load the old stuff at all.

**Comment by claymccoy** [comment]
Yes,  dashboard code would need a link to load the old history.
